const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Addidas slim shirt',
      slug: 'addidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 110,
      countInStock: 11,
      brand: 'Addidas',
      rating: 5,
      numReviews: 11,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 15,
      brand: 'Nike',
      rating: 4,
      numReviews: 15,
      description: 'high quality pants',
    },
    {
      name: 'Addidas slim pant',
      slug: 'Addidas-slim-pant',
      category: 'Addidas',
      image: '/images/p4.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
  ],
};

export default data;
